EntityBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: EntityBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        facebook_id:
            type: string
            lenght: 255
            nullable: true
        facebook_access_token:
            type: string
            lenght: 255
            nullable: true
    lifecycleCallbacks: {  }
